name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: ./.github/workflows/python-lint.yml
  coverage:
    needs: [ lint ]
    uses: ./.github/workflows/coverage.yml
  tests:
    needs: [ coverage ]
    uses: ./.github/workflows/python-package.yml
