name: Python Lint Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Python Lint Check
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v1
      - uses: marian-code/python-lint-annotate@v3
