name: Python Lint Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Python Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Cache
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python -m pip install -r requirements-dev.txt

      - uses: marian-code/python-lint-annotate@v3
        with:
          python-root-list: "src/* tests/*"
          use-pycodestyle: false
          use-mypy: true
          use-vulture: true
          extra-pylint-options: "--output-format=colorized"
          python-version: "3.10"
